name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_app-backend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy to Local Container
        run: |
          echo "Eski konteynerni to'xtatish..."
          docker stop my-app-container || true
          docker rm my-app-container || true
          
          echo "Yangi imijni yuklash..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_app-backend:latest
          
          echo "Konteynerni ishga tushirish..."
          docker run -d --name my-app-container -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my_app-backend:latest
          
          echo "Deployment tugadi! Loglarni tekshirish uchun: docker logs my-app-container"
